dist: xenial
language: python
python: "3.6"
cache: pip

matrix:
  include:
    # Run tests
    - services:
        - postgresql
      install:
        - "pip install -e ."
        - "pip install -r requirements-dev.txt"
        - python manage.py collectstatic
      script:
        - flake8
        - mypy .
        - py.test
        - createdb nurseconnect_registration
        - python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
        - black --check .
        - isort -c -rc .

    # Create docker image on merge to develop
    - sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/nurseconnect-registration:develop
        - REGISTRY_USER=praekeltorgdeploy
        # REGISTRY_PASS
        - secure: "zRPyTjae6do/yO+jwtqveywZ9VwSDOeOG+HjHWeiLPSTjUeV+5LJ+K8da/08Z6InsIKC8I0mI7fhopGqf54klP5bQjdRm8x0W03NJwJ8k/R9cBtnrYuj5W/XI/ZW+Ii0jSwNFSaQItkAr4IrlTLBbagCdiq9jQDKg9dIboRK9lfkulI6QkMbWqS4l0GO/zmB6IiZq/HuDkdLko08Yu74vpx1DFnIcYU15o2vXXVueCbmLAySreespaKMGH7QcMlKaGlPOE8CbVT1JKrQX6kXNQY9elubUqMd3ti93sDVuNZVfEaQpsX3kk6oTz7zJBxZjwmhtSGbYU8Dn2tSHu9aQac9JJEqphq6VO39Kc0VsaO1Vu42k9idV63X/0ZqcuUeEy1YITI1RHkCvN3GKSW/XKzwuKyn+b0myH53bGSp809NcQNinh346OToQBbTO2kDGEZZDh/ab72chGOQSexRMYqZPywr00/CDFNzZJo73IxKo/jf8GlM6cY75sWZj1BxkcwHIGa49a863/ZOGFiIiRjf/gs6ka+yDIwyQOr0wPOEdQpdXuLyCeeLO2lpAK0jhBzfSqT4rM68vcYnaUAXvMpwyCttHmqc1ur1i7ayYnQV0h6BMQP6JsMMZJi9nI+fIleLhdH7BYrfLjpb6HXoHd1AZLT+iyUIuFSlnfgtt/4="
      before_script:
        - docker pull "$IMAGE_NAME" || true
        - pip install -r seaworthy/requirements.txt
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .
        - (cd seaworthy; py.test -v --ncreg-image "$IMAGE_NAME" test.py)

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
      deploy:
        provider: script
        script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
        on:
          branch: develop
